pipeline {
    agent any

    environment {
        // Define environment variables for email credentials and website URL
        WEBSITE_MONITORING                                     =    "${WEBSITE_MONITORING}"
        EMAIL_SENDER                                           =    "${EMAIL_SENDER}"
        EMAIL_PASSWORD                                         =    credentials("EMAIL_PASSWORD")
        EMAIL_RECEIVER_GROUP                                   =    "${EMAIL_RECEIVER_GROUP}"
    }

    stages {
        stage('Checkout Code') {
            steps {
                // Clona el repositorio donde está el script Python
                checkout scm
            }
        }

        stage('Run Website Monitoring Script') {
            steps {
                // Ejecuta el script de monitoreo
                script {
                    sh '''
                        python3 ../monitoring/website_monitor.py
                    '''
                }
            }
        }
    }

    post {
        always {
            // Notificación al final del pipeline
            echo 'Pipeline finished'
        }
    }
}
